Parameters:

  KeyName:
    Description: Enter the Key Name
    Type: AWS::EC2::KeyPair::KeyName    

Resources:  
  
  MYALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Name: ALB-Target-Group
      Port: 80
      Protocol: HTTP
      VpcId: '{{resolve:ssm:/parameters/stacks/VPC/id}}'

  
  
  MYALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Name: My-Application-Load-Balancer
      SecurityGroups:
        - '{{resolve:ssm:/parameters/stacks/security-groups/ALB/id}}'
      Subnets:
        - '{{resolve:ssm:/parameters/stacks/public-subnet-1/id}}'
        - '{{resolve:ssm:/parameters/stacks/public-subnet-2/id}}'
      Type: application


  ALBListener:
    DependsOn: MYALB
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MYALBTargetGroup 
      LoadBalancerArn: !Ref MYALB
      Port: 80 
      Protocol: HTTP

  ALBSSM:
    Type: AWS::SSM::Parameter
    DependsOn: MYALB
    Properties:
      Name: /parameters/stacks/ALB/id
      Type: String
      Value: !GetAtt MYALB.DNSName


  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-launch-template-for-auto-scaling'
      LaunchTemplateData:
        SecurityGroupIds:
          - '{{resolve:ssm:/parameters/stacks/security-groups/web-server/id}}'
        InstanceType: t2.nano
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        KeyName: !Ref KeyName
        UserData:
          Fn::Base64: 
            !Sub |          
              #!/bin/bash
              yum update -y
              sudo yum install -y httpd httpd-tools mod_ssl
              sudo systemctl enable httpd 
              sudo systemctl start httpd
              sudo amazon-linux-extras enable php7.4
              service httpd restart 

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup 
    DependsOn: MYALBTargetGroup 
    Properties:
      AutoScalingGroupName: MyASG
      MaxSize: 3
      MinSize: 1
      DesiredCapacity: 1
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
      VPCZoneIdentifier:
        - '{{resolve:ssm:/parameters/stacks/private-subnet-1/id}}'
        - '{{resolve:ssm:/parameters/stacks/private-subnet-2/id}}'
      TargetGroupARNs:
        - !Ref MYALBTargetGroup



  CloudFrontDistribution: 
    DependsOn: ALBSSM
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MYALB.DNSName
            Id: application-load-balancer
            CustomOriginConfig:
                OriginProtocolPolicy : http-only
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          DefaultTTL: 86400 
          MaxTTL: 31536000
          MinTTL: 0
          SmoothStreaming: false
          TargetOriginId: application-load-balancer
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
        HttpVersion: http2
        Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: true       


      





  
 