Resources:
  
  DBSubnetGorup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: My Subnet Group
      SubnetIds:
        - '{{resolve:ssm:/parameters/stacks/private-subnet-1/id}}'
        - '{{resolve:ssm:/parameters/stacks/private-subnet-2/id}}'
      Tags:
        - Key: Name
          Value: My Subnet Group  

  MySQLDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      MasterUsername: jayant
      MasterUserPassword: qwertysss
      DBSubnetGroupName: !Ref DBSubnetGorup
      DBName: mysqldb
      Engine: MySQL
      EngineVersion: 5.7.40
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: false
      DBInstanceIdentifier: database-12
      AllocatedStorage: 20
      VPCSecurityGroups:
        - '{{resolve:ssm:/parameters/stacks/security-groups/database/id}}'